cookie_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("booths/", include("cookie_booths.urls")),
    path("troops/", include("troops.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

troops/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views


app_name = "troops"
urlpatterns = [
    # Troops Home
    path("", views.TroopListView.as_view(), name="troops"),
    # Create New Troop
    path("new/", views.TroopCreateView.as_view(), name="create_troop"),
    # Edit Troop Page
    path("edit/<int:pk>/", views.TroopUpdateView.as_view(), name="edit_troop"),
    # Delete Troop
    path(
        "confirm_delete/<int:pk>/", views.TroopDeleteView.as_view(), name="delete_troop"
    ),
]

troops/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver


class TicketParameters(models.Model):
    small_troop_total_tickets_per_week = models.IntegerField(default=5)
    small_troop_golden_tickets_per_week = models.IntegerField(default=1)
    medium_troop_additional_golden_tickets = models.IntegerField(default=1)
    large_troop_additional_golden_tickets = models.IntegerField(default=2)

    @property
    def get_small_troop_total_tickets_per_week(self):
        return self.small_troop_total_tickets_per_week

    @property
    def get_small_troop_golden_tickets_per_week(self):
        return self.small_troop_golden_tickets_per_week
    
    @property
    def get_medium_troop_total_tickets_per_week(self):
        return int(self.small_troop_total_tickets_per_week * 2)

    @property
    def get_medium_troop_golden_tickets_per_week(self):
        return int(self.small_troop_golden_tickets_per_week + 
            self.medium_troop_additional_golden_tickets)

    @property
    def get_large_troop_total_tickets_per_week(self):
        return int(self.small_troop_total_tickets_per_week * 3)
        
    @property
    def get_large_troop_golden_tickets_per_week(self):
        return int(self.small_troop_golden_tickets_per_week +
            self.large_troop_additional_golden_tickets)

    # We only EVER need one instance of this model.
    def save(self, *args, **kwargs):
        self.id = 1
        super().save(*args, **kwargs)


class TroopSize(models.Model):
    medium_troop_size = models.IntegerField(default=8)
    large_troop_size = models.IntegerField(default=10)

    @property
    def get_medium_troop_size(self):
        return int(self.medium_troop_size)

    @property
    def get_large_troop_size(self):
        return int(self.large_troop_size)

    # We only EVER need one instance of this model.
    def save(self, *args, **kwargs):
        self.id = 1
        super().save(*args, **kwargs)


class Troop(models.Model):
    troop_number = models.IntegerField(unique=True)
    troop_cookie_coordinator = models.EmailField(null=True)

    troop_size = models.SmallIntegerField(default=0)
    troop_level = models.SmallIntegerField(
        choices=settings.GIRL_SCOUT_TROOP_LEVELS_WITH_NONE, default=0
    )

    total_booth_tickets_per_week = models.PositiveSmallIntegerField(default=0)
    booth_golden_tickets_per_week = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name_plural = "troops"
        verbose_name = "troop"

    def __str__(self):
        return "Troop " + str(self.troop_number)


@receiver(pre_save, sender=Troop)
def update_troop(sender, instance, **kwargs):
    # This really should only care about setting/updating these after creation, but there is always the chance
    # A troop could be updated after the fact. In that case, if they've booked more blocks than they should've,
    # oh well.
    if not TroopSize.objects.first():
        TroopSize.objects.create()
    if not TicketParameters.objects.first():    
        TicketParameters.objects.create()
    update_tickets(instance)


@receiver(post_save, sender=TroopSize)
@receiver(post_save, sender=TicketParameters)
def update_all_troops(sender, instance, **kwargs):
    troops = Troop.objects.all()
    for troop in troops:
        update_tickets(troop=troop)
        troop.save()

def update_tickets(troop):
    # This really should only care about setting/updating these after creation, but there is always the chance
    # A troop could be updated after the fact. In that case, if they've booked more blocks than they should've,
    # oh well.
    try:
        if troop.troop_size >= TroopSize.objects.first().get_large_troop_size:
            troop.total_booth_tickets_per_week = (
                TicketParameters.objects.first().get_large_troop_total_tickets_per_week
            )
            troop.booth_golden_tickets_per_week = (
                TicketParameters.objects.first().get_large_troop_golden_tickets_per_week
            )
            return

        if troop.troop_size >= TroopSize.objects.first().get_medium_troop_size:
            troop.total_booth_tickets_per_week = (
                TicketParameters.objects.first().get_medium_troop_total_tickets_per_week
            )
            troop.booth_golden_tickets_per_week = (
                TicketParameters.objects.first().get_medium_troop_golden_tickets_per_week
            )
            return

        troop.total_booth_tickets_per_week = (
            TicketParameters.objects.first().get_small_troop_total_tickets_per_week
        )
        troop.booth_golden_tickets_per_week = (
            TicketParameters.objects.first().get_small_troop_golden_tickets_per_week
        )
    except AttributeError:
        # Do not try to update if we cannot find the Parameters yet. 
        pass

troops/forms.py
from django import forms
from django.utils.translation import gettext as _

from .models import Troop


class TroopForm(forms.ModelForm):
    class Meta:
        model = Troop
        fields = [
            "troop_number",
            "troop_cookie_coordinator",
            "troop_level",
            "troop_size",
        ]

        labels = {
            "troop_number": _("Troop Number"),
            "troop_cookie_coordinator": _("Troop Cookie Coordinator Username"),
            "troop_level": _("Troop Level"),
            "troop_size": _("Troop Size"),
        }

    def clean(self):
        # We want to make absolutely sure that we are not duplicating a troop. We should be able to find this uniquely
        # by troop number
        if Troop.objects.filter(troop_number=self.cleaned_data["troop_number"]):
            cleaned_troop_id = Troop.objects.get(
                troop_number=self.cleaned_data["troop_number"]
            ).troop_number

            if cleaned_troop_id != self.troop_number or self.troop_number is None:
                self.add_error(
                    "troop_number",
                    "Troop number is already taken. Please choose a unique troop number.",
                )
                raise forms.ValidationError("Invalid Troop number!")

    def __init__(self, *args, **kwargs):
        # This is used to add booth_id to check if we're duplicating an item on edit.
        try:
            self.troop_number = kwargs.pop("troop_number")
        except KeyError:
            self.troop_number = None
        super(TroopForm, self).__init__(*args, **kwargs)

troops/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import TroopForm
from .models import Troop


# -----------------------------------------------------------------------
# Troop General User Functions
# -----------------------------------------------------------------------
class TroopListView(LoginRequiredMixin, ListView):
    model = Troop
    template_name = "troops.html"


# -----------------------------------------------------------------------
# Troop Admin Functions
# -----------------------------------------------------------------------
class TroopCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = "troops.add_troop"
    form_class = TroopForm
    success_url = reverse_lazy("troops:troops")
    template_name = "new_troop.html"


class TroopUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = "troops.change_troop"
    model = Troop
    fields = ["troop_number", "troop_cookie_coordinator", "troop_level", "troop_size"]
    success_url = reverse_lazy("troops:troops")
    template_name = "edit_troop.html"


class TroopDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    """Delete an existing booth location"""

    permission_required = "troops.delete_troop"
    model = Troop
    template_name = "troop_confirm_delete.html"
    success_url = reverse_lazy("troops:troops")

troops/templates/edit_troop.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Troop Editor
{% endblock title %}

{% block page_header %}
  <h2>Edit troop</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'troops:edit_troop' troop.pk %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="mb-3">
      <button name="submit">Update Troop</button>
    </div>
  </form>
{% endblock content %}

troops/templates/new_troop.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Create Troop
{% endblock title %}

{% block page_header %}
  <h2>Add a new troop</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'troops:create_troop' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="mb-3">
      <button name="submit">Submit</button>
    </div>
  </form>
{% endblock content %}

troops/templates/troop_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Delete Troop
{% endblock title %}

{% block page_header %}
  <h2>Delete troop</h2>
{% endblock page_header %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

troops/templates/troops.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Available Troops
{% endblock title %}

{% block page_header %}
  <h2>Troops</h2>
{% endblock page_header %}


{% block content %}
<table id="troops" class="table table-striped table-bordered">
	<thead>
    	<tr>
        	<th>Troop ID</th>
			<th>Troop Coordinator</th>
            {% if perms.troops.change_troop or perms.troops.delete_troop %}
                <th>Actions</th>
            {% endif %}
		</tr>
	</thead>
	<tbody>

		{% for troop in troop_list %}
			<tr>
				<td>{{ troop.troop_number }}</td>
                <td>{{ troop.troop_cookie_coordinator }}</td>
				<td>

                    {% if perms.troops.change_troop %}
                        <a href="{% url 'troops:edit_troop' troop.pk %}">Edit Troop</a> |
                    {% endif %}

                    {%  if perms.troops.delete_troop %}

                        <a href="{% url 'troops:delete_troop' troop.pk %}">Delete Troop</a>
                    {% endif %}
                </td>
			</tr>
		{% endfor %}

        {% if perms.troops.add_troop %}
            <tr>
                {% if perms.troops.add_troop or perms.troop.troops_deletion %}

                    <td colspan="4"><a href="{% url 'troops:create_troop' %}">Add New Troop</a></td>
                {% else %}
                    <td colspan="3"><a href="{% url 'troops:create_troop' %}">Add New Troop</a></td>
                {% endif %}
            </tr>
        {% endif %}
	</tbody>
</table>

{% endblock content %}