cookie_booths/urls.py
from django.urls import path
from . import views


app_name = "cookie_booths"
urlpatterns = [
    # Create New Booth
    path("new/", views.create_new_booth_location, name="new_location"),
    # Booths Home
    path("edit/", views.booth_editor, name="booth_locations"),
    # Edit Booth Page
    path("edit/<int:booth_id>/", views.edit_booth_location, name="edit_location"),
    # Edit Booth Hours
    path(
        "edit/<int:booth_id>/hours/",
        views.edit_booth_location_hours,
        name="edit_booth_hours",
    ),
    # Delete Booth
    path(
        "confirm_delete/<int:pk>/",
        views.BoothLocationDelete.as_view(),
        name="delete_booth",
    ),
    # Manage Booth Blocks Home
    path("blocks/", views.booth_blocks, name="booth_blocks"),
    # Your Booth Reservations
    path("blocks/reservations/", views.booth_reservations, name="booth_reservations"),
    # Make Booth Reservation
    path(
        "blocks/reservations/<int:daisy>/<int:block_id>",
        views.reserve_block,
        name="block_reservation",
    ),
    # Cancel Booth Reservation
    path(
        "blocks/reservations/cancel/<int:daisy>/<int:block_id>",
        views.cancel_block,
        name="block_cancellation",
    ),
    # Hold Booth For Cookie Captains
    path(
        "blocks/cchold/<int:block_id>",
        views.hold_block_for_cookie_captain,
        name="hold_block_for_cookie_captain",
    ),
    # Cancel Holding Booth For Cookie Captains
    path(
        "blocks/cchold/cancel/<int:block_id>",
        views.cancel_hold_for_cookie_captain,
        name="cancel_hold_for_cookie_captain",
    ),
    # User Enable Booth by Block
    path(
        "blocks/enable_blocks",
        views.enable_location_by_block,
        name="enable_location_by_block",
    ),
    # AJAX Enable Booth by Block
    path(
        "blocks/enable_blocks/<int:block_id>",
        views.ajax_enable_location_by_block,
        name="ajax_enable_location_by_block",
    ),
    # AJAX Disable Booth by Block
    path(
        "blocks/disable_blocks/<int:block_id>",
        views.ajax_disable_location_by_block,
        name="ajax_disable_location_by_block",
    ),
    # User Enable Booth Day
    path("blocks/enable_booth_days", views.enable_or_disable_day, name="enable_day"),
    # AJAX Enable Booth by Day
    path(
        "blocks/enable_booth_days/enable",
        views.enable_location_by_day,
        name="ajax_enable_day",
    ),
    # AJAX Disable Booth by Day
    path(
        "blocks/enable_booth_days/disable",
        views.disable_location_by_day,
        name="ajax_disable_day",
    ),
    #
    path("enable_ffa", views.enable_all_locations_ffa, name="enable_ffa"),
]

cookie_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("booths/", include("cookie_booths.urls")),
    path("troops/", include("troops.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

cookie_booths/models.py
from datetime import timedelta, datetime
from pytz import utc

from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone

DAYS_OF_WEEK = [
    (0, "Monday"),
    (1, "Tuesday"),
    (2, "Wednesday"),
    (3, "Thursday"),
    (4, "Friday"),
    (5, "Saturday"),
    (6, "Sunday"),
]

class BoothLocation(models.Model):
    """Contains data relevant for booths"""

    # ID is referenced via Django object ID
    booth_location = models.CharField(max_length=300)
    booth_address = models.CharField(max_length=300)

    booth_enabled = models.BooleanField(default=False)

    booth_block_level_restrictions_start = models.SmallIntegerField(
        choices=settings.GIRL_SCOUT_TROOP_LEVELS_WITH_NONE, default=0
    )
    booth_block_level_restrictions_end = models.SmallIntegerField(
        choices=settings.GIRL_SCOUT_TROOP_LEVELS_WITH_NONE, default=0
    )

    booth_requires_masks = models.BooleanField(default=False)
    booth_is_outside = models.BooleanField(default=False)

    booth_notes = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name_plural = "booth locations"
        verbose_name = "booth location"

    def __str__(self):
        return self.booth_location

    def update_hours(self):
        # We need to create or delete booth days, or update their hours, based on new hours, and
        # we have a few steps for this
        hours = BoothHours.objects.get(booth_location=self)

        # If no date is set for either start or end date, delete all days owned by this booth
        if hours.booth_start_date is None or hours.booth_end_date is None:
            BoothDay.objects.filter(booth=self).delete()
            return

        # Delete any days outside of the new start/end date - this will cascade down to the blocks
        BoothDay.objects.filter(
            Q(booth=self),
            Q(booth_day_date__lt=hours.booth_start_date)
            | Q(booth_day_date__gt=hours.booth_end_date),
        ).delete()

        # Go through each day between the new start and end date
        for date in self.__daterange(hours.booth_start_date, hours.booth_end_date):
            # Figure out what day of the week it is, and either:
            # 1. If we're closed that day, delete a day if it's present
            if (
                ((date.weekday() == 0) and (not hours.monday_open))
                or ((date.weekday() == 1) and (not hours.tuesday_open))
                or ((date.weekday() == 2) and (not hours.wednesday_open))
                or ((date.weekday() == 3) and (not hours.thursday_open))
                or ((date.weekday() == 4) and (not hours.friday_open))
                or ((date.weekday() == 5) and (not hours.saturday_open))
                or ((date.weekday() == 6) and (not hours.sunday_open))
            ):
                BoothDay.objects.filter(booth=self, booth_day_date=date).delete()
            # 2. If we're open, add or update those hours
            else:
                if date.weekday() == 0:  # Monday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.monday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.monday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.monday_golden_ticket)
                elif date.weekday() == 1:  # Tuesday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.tuesday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.tuesday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.tuesday_golden_ticket)
                elif date.weekday() == 2:  # Wednesday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.wednesday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.wednesday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.wednesday_golden_ticket)
                elif date.weekday() == 3:  # Thursday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.thursday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.thursday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.thursday_golden_ticket)
                elif date.weekday() == 4:  # Friday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.friday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.friday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.friday_golden_ticket)
                elif date.weekday() == 5:  # Saturday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.saturday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.saturday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.saturday_golden_ticket)
                else:  # Sunday
                    self.add_or_update_day(
                        date,
                        datetime.combine(date, hours.sunday_open_time, tzinfo=utc),
                        datetime.combine(date, hours.sunday_close_time, tzinfo=utc),
                    )
                    self.update_golden_day(date, hours.sunday_golden_ticket)

        return

    def update_booth(self):
        hours = BoothHours.objects.get(booth_location=self)
        for date in self.__daterange(hours.booth_start_date, hours.booth_end_date):
            if (
                ((date.weekday() == 0) and hours.monday_open)
                or ((date.weekday() == 1) and hours.tuesday_open)
                or ((date.weekday() == 2) and hours.wednesday_open)
                or ((date.weekday() == 3) and hours.thursday_open)
                or ((date.weekday() == 4) and hours.friday_open)
                or ((date.weekday() == 5) and hours.saturday_open)
                or ((date.weekday() == 6) and hours.sunday_open)
            ):
                booth_day = self.__booth_day_exist(date)
                if self.booth_enabled:
                    booth_day.enable_day()
                else:
                    booth_day.disable_day()

        return

    def add_or_update_day(self, date, open_time, close_time):
        # First see if we have a Booth_Day existing for that date. If so, grab it and update the open/close time
        booth_day = self.__booth_day_exist(date=date)

        # Set the hours
        booth_day.add_or_update_hours(open_time, close_time)
        booth_day.save()

        return

    def update_golden_day(self, date, is_golden_booth):
        # First see if we have a Booth_Day existing for that date. If so, grab it and update the open/close time
        booth_day = self.__booth_day_exist(date=date)

        # Set the golden ticket
        booth_day.change_golden_status(is_golden_booth=is_golden_booth)
        booth_day.save()

        return

    def __daterange(self, start_date, end_date):
        # Need +1 to be inclusive of the end date
        for n in range(int((end_date - start_date).days) + 1):
            yield start_date + timedelta(n)

    def __booth_day_exist(self, date):
        try:
            booth_day = BoothDay.objects.get(booth=self, booth_day_date=date)

        except BoothDay.DoesNotExist:
            # If it doesn't exist yet, create it
            booth_day = BoothDay.objects.create(
                booth=self,
                booth_day_date=date,
                booth_day_enabled=False,
                booth_day_hours_set=False,
            )

        return booth_day


class BoothHours(models.Model):
    class Meta:
        verbose_name_plural = "Booth hours"

    def __str__(self):
        # Easier to use admin names
        return f"{self.booth_location} Hours"

    booth_location = models.OneToOneField(
        BoothLocation, null=True, on_delete=models.CASCADE
    )

    booth_start_date = models.DateField(blank=True, null=True)
    booth_end_date = models.DateField(blank=True, null=True)

    sunday_open = models.BooleanField(default=False)
    sunday_golden_ticket = models.BooleanField(default=False)
    sunday_open_time = models.TimeField(blank=True, null=True)
    sunday_close_time = models.TimeField(blank=True, null=True)

    monday_open = models.BooleanField(default=False)
    monday_golden_ticket = models.BooleanField(default=False)
    monday_open_time = models.TimeField(blank=True, null=True)
    monday_close_time = models.TimeField(blank=True, null=True)

    tuesday_open = models.BooleanField(default=False)
    tuesday_golden_ticket = models.BooleanField(default=False)
    tuesday_open_time = models.TimeField(blank=True, null=True)
    tuesday_close_time = models.TimeField(blank=True, null=True)

    wednesday_open = models.BooleanField(default=False)
    wednesday_golden_ticket = models.BooleanField(default=False)
    wednesday_open_time = models.TimeField(blank=True, null=True)
    wednesday_close_time = models.TimeField(blank=True, null=True)

    thursday_open = models.BooleanField(default=False)
    thursday_golden_ticket = models.BooleanField(default=False)
    thursday_open_time = models.TimeField(blank=True, null=True)
    thursday_close_time = models.TimeField(blank=True, null=True)

    friday_open = models.BooleanField(default=False)

cookie_booths/templates/cookie_booths/base.html
{% load bootstrap4 %}
{% load static %}


<! doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Crystal Falls Service Unit - Cookie Booths</title>
  <link rel="shortcut icon" type="image/png" href="{% static "cookie_booths/favicon.ico" %}"/>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="navbar-brand">Crystal Falls Service Unit</div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cookie_booths:index' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cookie Booths</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'cookie_booths:booth_locations' %}">Booth Locations</a>

            {% if perms.cookie_booths.booth_loc_creation %}
                <a class="dropdown-item" href="{% url 'cookie_booths:new_location' %}">New Booth Location</a>
            {%  endif %}
            {% if perms.cookie_booth.enable_day %}
                <a class="dropdown-item" href="{% url 'cookie_booths:enable_location_by_block' %}">Enable Booths by Block</a>
                <a class="dropdown-item" href="{% url 'cookie_booths:enable_day' %}">Enable Booths by Day</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'cookie_booths:booth_blocks' %}">Make Booth Reservations</a>
            <a class="dropdown-item" href="{% url 'cookie_booths:booth_reservations' %}">Manage Your Booth Reservations</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:troops' %}">Troops</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{%endblock content %}
    </div>
  </main>
</body>

</html>

cookie_booths/templates/cookie_booths/booth_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    Delete Booth
{% endblock title %}

{% block page_header %}
  <h2>Delete cookie booth</h2>
{% endblock page_header %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

cookie_booths/templates/cookie_booths/booths.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block page_header %}
  <h2>Booth Locations</h2>
{% endblock page_header %}

{% block title %}
    Booth Locations
{% endblock title %}

{% block content %}

{% if perms.cookie_booths.add_boothlocation %}
<div align="right">
<a role="button" class="btn btn-success" align="right" href="{% url 'cookie_booths:new_location' %}">
    <img src="{% static 'cookie_booths/icons8-add-24.png' %}">   
    Add Booth Location
</a>
</div>
<p>
<p>
{% endif %}

<table id="booths" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
    	<tr>
        	<th>Location</th>
			<th>Address</th>
            <th>Booth Outside</th>
            <th>Booth Requires Masks</th>
            <th>Booth Notes</th>
            {% if perms.cookie_booths.booth_loc_updates or perms.cookie_booths.booth_loc_deletes %}
                <th>Actions</th>
            {% endif %}
		</tr>
	</thead>
	<tbody>
		{% for booth in booths %}
			<tr>
				<td>{{ booth.booth_location }}</td>
				<td>{{ booth.booth_address }}</td>
                <td>{{ booth.booth_is_outside }}</td>
                <td>{{ booth.booth_requires_masks }}</td>
                <td>{{ booth.booth_notes }}</td>
				<td>
                    {% if perms.cookie_booths.booth_loc_updates %}
                        <a href="{% url 'cookie_booths:edit_location' booth.id %}">Edit Booth</a> |
                        <a href="{% url 'cookie_booths:edit_booth_hours' booth.id %}">Edit Hours</a> |
                    {% endif %}

                    {%  if perms.cookie_booths.booth_loc_deletes %}
                        <a href="{% url 'cookie_booths:delete_booth' booth.pk %}">Delete Booth</a>
                    {% endif %}
                </td>
			</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock content %}

cookie_booths/templates/cookie_booths/edit_booth.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    Booth Editor
{% endblock title %}

{% block page_header %}
  <h2>Edit cookie booth</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'cookie_booths:edit_location' booth.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="mb-3">
      <button name="submit">Update Cookie Booth</button>
    </div>
  </form>
{% endblock content %}

cookie_booths/templates/cookie_booths/edit_booth_hours.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}
    Booth Editor
{% endblock title %}

{% block page_header %}
  <h2>Edit cookie booth hours</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'cookie_booths:edit_booth_hours' booth.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form_errors form %}
    {% bootstrap_form form %}
    <div class="mb-3">
      <button name="submit">Update Booth Hours</button>
    </div>
  </form>
{% endblock content %}

{% block extra_js %}

  {{ form.media }}

  <script src="{% static 'cookie_booths/js/toggle_controls.js' %}"></script>
{% endblock extra_js %}

cookie_booths/templates/cookie_booths/enable_blocks.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    {{ page_title }}
{% endblock title %}

{% block page_header %}
    <h2>{{ page_title }}</h2>
{% endblock page_header %}


{% block content %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">

    <table id="booth_blocks" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Location</th>
                <th>Date</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody>
            {% for day in booth_days %}
                <tr>
                    <td>{{ day.booth.booth_location }}</td>
                    <td>{{ day.booth_day_date }}</td>
                    <td>
                        {% if day.booth_day_enabled %}
                            <input type="button" id="DisableBooth" value="Disable Day"
                                        onclick="DisableBooth({{ day.id }})">
                        {% else %}
                            <input type="button" id="EnableBooth" value="Enable Day"
                                        onclick="EnableBooth({{ day.id }})">
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
    $(document).ready(function() {
        $('#booth_blocks').DataTable( {
    	    "paging":   false,
        } );
    } );
    </script>

    <script>
        function EnableBooth(booth_id) {
            $.ajax({

                    url: location.origin + "/booths/blocks/enable_booth_days/enable",
                    type: 'POST',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        booth_id: booth_id
                    },
                    success: function (){
                        {
                            window.location.reload()
                        }
                    }
            });
        }

        function DisableBooth(booth_id) {
            $.ajax({
                    url: location.origin + "/booths/blocks/enable_booth_days/disable",
                    type: 'POST',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        booth_id: booth_id
                    },
                    success: function (){
                        {
                            window.location.reload()
                        }
                    }
            });
        }
    </script>


{% endblock content %}

cookie_booths/templates/cookie_booths/free_for_all.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

<!-- Load jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRlWwo3Xr2N/7cl01V24b1n6zRLCVJc1Et0k0ST3I" crossorigin="anonymous"></script>
{% bootstrap_javascript %}

{% block title %}
    Booth Editor
{% endblock title %}

{% block page_header %}
    <h2>Enable Free For All</h2>
{% endblock page_header %}


{% block content %}
  <form action="{% url 'cookie_booths:enable_ffa' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {{ form.media }}
    <div class="mb-3">
      <button name="submit">Enable Free For All</button>
    </div>
  </form>
{% endblock content %}

cookie_booths/templates/cookie_booths/index.html
{% extends "cookie_booths/base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">C is for cookie and cookies are for me</h1>

        <p class="lead">I like cookies</p>
        {% if not user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
        {% endif %}
    </div>
{% endblock content %}

cookie_booths/templates/cookie_booths/new_booth_location.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    Booth Editor
{% endblock title %}

{% block page_header %}
  <h2>Add a new cookie booth</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'cookie_booths:new_location' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="mb-3">
      <button name="submit">Next</button>
    </div>
  </form>
{% endblock content %}